/* List of all Edges in GTSFM Visualization Graph. Imported in LandingPageGraph.js.

Author: Adi Singh
*/

const edge_list = [
    ["Image Loader", "Image Retriever"],
    ["Image Loader", "Relative Pose Priors"],
    ["Image Loader", "Absolute Pose Priors"],
    ["Image Loader", "Camera Instrinsice"],
    ["Image Loader", "Images"],
    ["Image Loader", "Image Shapes"],
    ["Image Retriever", "Image Pair Indices"],
    ["Two-View Bundle Adjustment", "Optimized Relative Rotation"],
    ["Two-View Bundle Adjustment", "Optimized Relative Translation"],
    ["Two-View Bundle Adjustment", "Inlier Correspondences"],
    ["Triangulated Points", "Two-View Bundle Adjustment"],
    ["Camera Intrinsics", "Two-View Bundle Adjustment"],
    ["Keypoints", "Two-View Bundle Adjustment"],
    ["Verified Correspondences", "Two-View Bundle Adjustment"],
    ["Relative Rotation", "Two-View Bundle Adjustment"],
    ["Relative Translation", "Two-View Bundle Adjustment"],
    ["Verifier", "Verified Correspondences"],
    ["Verifier", "Relative Rotation"],
    ["Verifier", "Relative Translation"],
    ["Verifier", "Inlier Ratio"],
    ["Keypoints", "Verifier"],
    ["Putative Correspondences", "Verifier"],
    ["Camera Intrinsics", "Verifier"],
    ["Images", "DetectorDescriptor"],
    ["DetectorDescriptor", "Keypoints"],
    ["DetectorDescriptor", "Descriptors"],
    ["Keypoints", "Matcher"],
    ["Descriptors", "Matcher"],
    ["Image Shapes", "Matcher"],
    ["Matcher", "Putative Correspondences"],
    ["View-Graph Estimator", "View-Graph Relative Rotations"],
    ["View-Graph Estimator", "View-Graph Relative Translations"],
    ["View-Graph Estimator", "View-Graph Correspondences"],
    ["Optimized Relative Rotation", "View-Graph Estimator"],
    ["Camera Intrinsics", "View-Graph Estimator"],
    ["Inlier Correspondences", "View-Graph Estimator"],
    ["Keypoints", "View-Graph Estimator"],
    ["Rotation Averaging", "Global Rotations"],
    ["View-Graph Relative Rotations", "Rotation Averaging"],
    ["Relative Pose Priors", "Rotation Averaging"],
    ["View-Graph Relative Translations", "Translation Averaging"],
    ["Global Rotations", "Translation Averaging"],
    ["Absolute Pose Priors", "Translation Averaging"],
    ["Relative Pose Priors", "Translation Averaging"],
    ["Translation Averaging", "Global Translations"],
    ["View-Graph Correspondences", "Data Association"],
    ["Global Rotations", "Data Association"],
    ["Global Translations", "Data Association"],
    ["Camera Intrinsics", "Data Association"],
    ["Data Association", "3D Tracks"],
    ["Global Bundle Adjustment", "Optimized Camera Poses"],
    ["Global Bundle Adjustment", "Optimized 3D Tracks"],
    ["Absolute Pose Priors", "Global Bundle Adjustment"],
    ["Relative Pose Priors", "Global Bundle Adjustment"],
    ["Camera Intrinsics", "Global Bundle Adjustment"],
    ["Global Translations", "Global Bundle Adjustment"],
    ["Global Rotations", "Global Bundle Adjustment"],
    ["3D Tracks", "Global Bundle Adjustment"],
    ["Multi-view Stereo", "Dense Colored 3D Point Cloud"],
    ["Images", "Multi-view Stereo"],
    ["Optimized Camera Poses", "Mult-view Stereo"],
    ["Optimized 3D Tracks", "Multi-view Stereo"],

]

module.exports = edge_list;