/* List of all Edges in GTSFM Visualization Graph. Imported in LandingPageGraph.js.

Author: Adi Singh
*/

const edge_list = [['Scene Image Directories', 'Scene Looper'], 
                        ['Scene Looper', 'Scene Directory'], 
                        ['DigiCamDB', 'Data Loader + Filter Invalid Edges'], 
                        ['Scene Directory', 'Data Loader + Filter Invalid Edges'], 
                        ['Data Loader + Filter Invalid Edges', 'Image i'], 
                        ['Image i', 'Detector'], ['Detector', 'Keypoints'], 
                        ['Keypoints', 'Verifier'], 
                        ['Keypoints', 'Keypoint Describer'], 
                        ['Image i', 'Keypoint Describer'], 
                        ['Keypoint Describer', 'Descriptors'], 
                        ['Descriptors', 'Putative Matcher'],
                        ['Data Loader + Filter Invalid Edges', 'Intrinsics'], 
                        ['Data Loader + Filter Invalid Edges', 'Image Pair Indices (i1,i2)'], 
                        ['Image Pair Indices (i1,i2)', 'Putative Matcher'], 
                        ['Putative Matcher', 'Putative Correspondence Indices'], 
                        ['Putative Correspondence Indices', 'Verifier'],
                        ['Intrinsics', 'Verifier'], 
                        ['Verifier', 'E matrix'], 
                        ['E matrix', 'Post-Processor'], 
                        ['Verifier', 'Verified Correspondence Indices'], 
                        ['Post-Processor', 'relative Rs: i2Ri1'], 
                        ['Post-Processor', 'relative ts: i2ti1'], 
                        ['Intrinsics', 'Bundler Calibrator'], 
                        ['Data Loader + Filter Invalid Edges', 'Images'],
                        ['Keypoints', 'Data Association w/ Track Filtering'], 
                        ['Verified Correspondence Indices', 'Data Association w/ Track Filtering'], 
                        ['relative Rs: i2Ri1', 'Largest Connected Component Extractor'], 
                        ['relative ts: i2ti1', 'Largest Connected Component Extractor'], 
                        ['Images', 'MVSNet'], 
                        ['Largest Connected Component Extractor', 'Pruned relative Rs (2): i2Ri1'], 
                        ['Pruned relative Rs (2): i2Ri1', 'Shonan'], 
                        ['Largest Connected Component Extractor', 'Pruned relative ts: i2ti1'], 
                        ['Pruned relative ts: i2ti1', '1d-SfM'], 
                        ['1d-SfM', 'absolute ts'], 
                        ['Shonan', 'absolute Rs'], 
                        ['absolute Rs', '1d-SfM'], 
                        ['absolute Rs', 'Bundler Calibrator'],
                        ['absolute ts', 'Bundler Calibrator'], 
                        ['Bundler Calibrator', 'Bundler Pinhole Cameras'], 
                        ['Bundler Pinhole Cameras', 'Data Association w/ Track Filtering'], 
                        ['Data Association w/ Track Filtering', 'Data Association GtsfmData'], 
                        ['Data Association GtsfmData', 'Optimizer'], 
                        ['Bundler Pinhole Cameras', 'Optimizer'], 
                        ['Optimizer', 'Bundle Adjustment GtsfmData'],
                        ['Bundle Adjustment GtsfmData', 'MVSNet'],
                        ['Bundle Adjustment GtsfmData', 'File Writer'],
                        ['Output Directory', 'File Writer'],
                        ['File Writer', 'SFMResult as files'],
                        ['MVSNet', 'Dense Point Cloud'], 
                        ['Dense Point Cloud', 'Triangulation'], 
                        ['Triangulation', 'Dense Mesh Reconstruction'], 
                        ['Dense Mesh Reconstruction', 'Aggregate'], 
                        ['Aggregate', 'Zipped Results for All Scenes']]

module.exports = edge_list;