# COLMAP Loader Configuration
_target_: gtsfm.loader.colmap_loader.ColmapLoader
colmap_files_dirpath: ??? # Required - path to COLMAP files directory
images_dir: ??? # Required - path to images directory
max_resolution: 760
