
CorrespondenceGenerator:
  _target_: gtsfm.frontend.correspondence_generator.det_desc_correspondence_generator.DetDescCorrespondenceGenerator

  
  detector_descriptor:
    _target_: gtsfm.frontend.cacher.detector_descriptor_cacher.DetectorDescriptorCacher
    detector_descriptor_obj:
      _target_: gtsfm.frontend.detector_descriptor.brisk.BRISKDetectorDescriptor
      max_keypoints: 5000

  matcher:
    _target_: gtsfm.frontend.cacher.matcher_cacher.MatcherCacher
    matcher_obj:
      _target_: gtsfm.frontend.matcher.twoway_matcher.TwoWayMatcher
      ratio_test_threshold: 0.8