CorrespondenceGenerator:
  _target_: gtsfm.frontend.correspondence_generator.image_correspondence_generator.ImageCorrespondenceGenerator

  matcher:
    _target_: gtsfm.frontend.cacher.image_matcher_cacher.ImageMatcherCacher
    matcher_obj:
      _target_: gtsfm.frontend.matcher.romav2.RoMaV2Matcher
      setting: precise
      min_confidence: 0.1
      max_keypoints: 8000

  aggregator:
    _target_: gtsfm.frontend.correspondence_generator.keypoint_aggregator.keypoint_aggregator_dedup.KeypointAggregatorDedup
    nms_merge_radius: 1e-4
