# SSH login credentials for remote cluster
username: YOUR_USERNAME_HERE

# Dask scheduler configuration, local
scheduler:
  port: 8788                 # Port for Dask scheduler to listen on
  dashboard: 8787        # Address for the Dask dashboard UI

# remote workers and SSH port
workers:
  host1.cc.gatech.edu: portnumber

# PostgreSQL connection settings (local to the scheduler)
database:
  host: localhost            # PostgreSQL host (usually localhost if tunneled)
  port: 5432                 # PostgreSQL port
  database: YOUR_DB_NAME        # Database name
  user: YOUR_DB_USERNAME             # Database username
  password: "YOUR_DB_PASSWORD"           # Database password
